// Auto-generated by scripts/reprice.js
import bebes from './bebes.json';
import boissons from './boissons.json';
import boucherie from './boucherie.json';
import entretien from './entretien.json';
import epices from './epices.json';
import frais from './frais.json';
import petitsFumes from './petits-fumes.json';
import poissonnerie from './poissonnerie.json';
import sec from './sec.json';
import volaille from './volaille.json';

export const byCategory = {
  'bebes': bebes as any,
  'boissons': boissons as any,
  'boucherie': boucherie as any,
  'entretien': entretien as any,
  'epices': epices as any,
  'frais': frais as any,
  'petits-fumes': petitsFumes as any,
  'poissonnerie': poissonnerie as any,
  'sec': sec as any,
  'volaille': volaille as any
};

const all = [
  ...(bebes as any),
  ...(boissons as any),
  ...(boucherie as any),
  ...(entretien as any),
  ...(epices as any),
  ...(frais as any),
  ...(petitsFumes as any),
  ...(poissonnerie as any),
  ...(sec as any),
  ...(volaille as any)
];
export default all as any;
